"""Backward-compatible facade for Bubo's SQLite state modules.

Schema lifecycle, runtime persistence, and aggregate reporting live in focused
modules. Existing callers continue to import their stable API from bubo.db.
"""

from bubo.db_reporting import (
    _parse_bound,
    _report_window,
    audit_rows,
    audit_rows_count,
    disputed_class_stats,
    disputed_finding_classes,
    findings_for,
    get_review_row,
    latency_summary,
    list_recent_reviews,
    metrics_summary,
    noise_trend,
    outcomes_for,
    outcomes_summary,
    policy_decisions_summary,
    provenance_summary,
    review_details_for,
    roi_proxy,
)
from bubo.db_runtime import (
    already_seen,
    count_inflight_workers,
    finding_seen,
    governance_decision_for,
    governance_decisions_for,
    latest_reviewed_row,
    posted_findings_for_outcome_sync,
    prompt_version,
    provenance_for,
    record,
    record_finding,
    record_finding_outcome,
    record_finding_outcome_sync_attempt,
    record_governance_decision,
    record_provenance,
    record_review_run_finish,
    record_review_run_start,
    review_health,
    review_run_id,
    status_age_seconds,
)
from bubo.db_schema import connect_db, ensure_column, init_db, init_dirs, read_db
from bubo.statuses import FindingStatus, ReviewMode, ReviewStatus

__all__ = [
    "FindingStatus",
    "ReviewMode",
    "ReviewStatus",
    "_parse_bound",
    "_report_window",
    "already_seen",
    "audit_rows",
    "audit_rows_count",
    "connect_db",
    "count_inflight_workers",
    "disputed_class_stats",
    "disputed_finding_classes",
    "ensure_column",
    "finding_seen",
    "findings_for",
    "get_review_row",
    "governance_decision_for",
    "governance_decisions_for",
    "init_db",
    "init_dirs",
    "latency_summary",
    "latest_reviewed_row",
    "list_recent_reviews",
    "metrics_summary",
    "noise_trend",
    "outcomes_for",
    "outcomes_summary",
    "policy_decisions_summary",
    "posted_findings_for_outcome_sync",
    "prompt_version",
    "provenance_for",
    "provenance_summary",
    "read_db",
    "record",
    "record_finding",
    "record_finding_outcome",
    "record_finding_outcome_sync_attempt",
    "record_governance_decision",
    "record_provenance",
    "record_review_run_finish",
    "record_review_run_start",
    "review_details_for",
    "review_health",
    "review_run_id",
    "roi_proxy",
    "status_age_seconds",
]
